def dictfetchall(cursor):
    """Return all rows from a cursor as a dict"""
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


queryListaLugares = ('SELECT \n'
                     '       DISTINCT idSistema, \n'
                     '       mue.nombre, \n'
                     '       lab.idLaboratorio || " " || lab.nombre || ":" || muela.posX || "," || muela.posY AS ubicacion, \n'
                     '       temperatura, \n'
                     '       pro.nombre AS protocolo, \n'
                     '       ba.posicion AS bandeja, \n'
                     '       mu.id AS id_muestra, \n'
                     '       mu.nombre AS muestra \n'
                     'FROM LabModule_almacenamiento AS alm \n'
                     'LEFT JOIN LabModule_bandeja AS ba \n'
                     'ON ba.almacenamiento_id = alm.idSistema \n'
                     'LEFT JOIN LabModule_muestraenbandeja AS meb \n'
                     'ON meb.idBandeja_id = ba.id \n'
                     'LEFT JOIN LabModule_muestra AS mu \n'
                     'ON mu.id = meb.idMuestra_id \n'
                     'LEFT JOIN LabModule_paso_muestras AS pam \n'
                     'ON pam.muestra_id = mu.id \n'
                     'LEFT JOIN LabModule_paso AS pa \n'
                     'ON pa.id = pam.paso_id \n'
                     'LEFT JOIN LabModule_protocolo AS pro \n'
                     'ON pro.id = pa.protocolo_id \n'
                     'LEFT JOIN LabModule_mueble AS mue \n'
                     'ON mue.id = alm.mueble_id \n'
                     'LEFT JOIN LabModule_muebleenlab AS muela \n'
                     'ON muela.idMueble_id = mue.id \n'
                     'LEFT JOIN LabModule_laboratorio AS lab \n'
                     'ON lab.idLaboratorio = muela.idLaboratorio_id \n'
                     'WHERE mue.tipo = "almacenamiento" \n')

queryDetalleSolicitudes = (' select \n'
                           '        ml.idLaboratorio_id,\n'
                           '        a.idSistema,\n'
                           '        me.nombre,\n'
                           '        ml.posX,\n'
                           '        ml.posY,\n'
                           '        b.posicion,\n'
                           '        mb.posX AS posXMuestra,\n'
                           '        mb.posY AS posYMuestra\n'
                           'from LabModule_solicitud s\n'
                           'join LabModule_solicitudmuestra m\n'
                           'on s.id = m.solicitud_id\n'
                           'join LabModule_muestraenbandeja mb\n'
                           'on m.muestra_id = mb.idMuestra_id\n'
                           'join LabModule_bandeja b\n'
                           'on mb.idBandeja_id=b.id\n'
                           'join LabModule_almacenamiento a\n'
                           'on b.almacenamiento_id = a.idSistema\n'
                           'join LabModule_mueble me\n'
                           'on a.mueble_id = me.id\n'
                           'join LabModule_muebleenlab ml\n'
                           'on a.mueble_id = ml.idMueble_id\n'
                           'where s.id =')
queryListaSolicitudes = ('select \n'
                         '      s.id AS idSolicitud,\n'
                         '      sm.tipo AS tipo,\n'
                         '      m.nombre AS nombreMuestra,\n'
                         '      sm.cantidad AS cantSolicitada,\n'
                         '      count(mb.id) AS cantExistente,\n'
                         '      s.fechaActual AS fecha,\n'
                         '      u.nombre_usuario AS solicitante,\n'
                         '      p.nombre AS paso,\n'
                         '      p.descripcion AS descPaso\n'
                         'from LabModule_solicitud s\n'
                         'join LabModule_usuario u\n'
                         'on s.solicitante_id = u.id\n'
                         'join LabModule_paso p\n'
                         'on s.paso_id = p.id\n'
                         'join LabModule_solicitudmuestra sm\n'
                         'on s.id = sm.solicitud_id\n'
                         'left join LabModule_muestraenbandeja mb\n'
                         'on sm.muestra_id = mb.idMuestra_id\n'
                         'left join LabModule_muestra m\n'
                         'on mb.idMuestra_id = m.id\n'
                         'where s.estado = "creada" \n'
                         'group by s.id')
queryBandejasMuestras = (' select \n'
                         '        ml.idLaboratorio_id,\n'
                         '        a.idSistema,\n'
                         '        me.nombre,\n'
                         '        ml.posX,\n'
                         '        ml.posY,\n'
                         '        b.posicion,\n'
                         '        mb.posX AS posXMuestra,\n'
                         '        mb.posY AS posYMuestra\n'
                         'from LabModule_muestraenbandeja mb\n'
                         'join LabModule_bandeja b\n'
                         'on mb.idBandeja_id=b.id\n'
                         'join LabModule_almacenamiento a\n'
                         'on b.almacenamiento_id = a.idSistema\n'
                         'join LabModule_mueble me\n'
                         'on a.mueble_id = me.id\n'
                         'join LabModule_muebleenlab ml\n'
                         'on a.mueble_id = ml.idMueble_id\n'
                         'where mb.idMuestra_id = ')
queryListaMuestrasAll = ('select\n'
                         '        m.id,\n'
                         '        m.nombre,\n'
                         '        m.valor,\n'
                         '        m.unidadBase,\n'
                         '        count(mb.id) as cant_muestras,\n'
                         '        m.controlado\n'
                         'from LabModule_muestra m\n'
                         'left join LabModule_muestraenbandeja mb\n'
                         'on m.id = mb.idMuestra_id\n'
                         'group by m.id')
queryListaMuestras = ('select\n'
                      '        m.id,\n'
                      '        m.nombre,\n'
                      '        m.valor,\n'
                      '        m.unidadBase,\n'
                      '        count(mb.id) as cant_muestras,\n'
                      '        m.controlado\n'
                      'from LabModule_muestra m\n'
                      'left join LabModule_muestraenbandeja mb\n'
                      'on m.id = mb.idMuestra_id\n'
                      'where m.activa = 1\n'
                      'group by m.id')
