def dictfetchall(cursor):
    """Return all rows FROM a cursor as a dict"""
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


queryListaLugares = ('SELECT\n'
                     '       DISTINCT "idSistema",\n'
                     '       m.nombre,\n'
                     '       l."idLaboratorio" || \' \' || l.nombre || \':\' || ml."posX" || \',\' || ml."posY" AS ubicacion,\n'
                     '       temperatura,\n'
                     '       p.nombre AS protocolo,\n'
                     '       b.posiciON AS bandeja,\n'
                     '       mu.id AS id_muestra,\n'
                     '       mu.nombre AS muestra\n'
                     'FROM "LabModule_almacenamiento" AS a\n'
                     'LEFT JOIN "LabModule_bandeja" AS b\n'
                     'ON b.almacenamiento_id = a."idSistema"\n'
                     'LEFT JOIN "LabModule_muestraenbandeja" AS mb\n'
                     'ON mb."idBandeja_id" = b.id\n'
                     'LEFT JOIN "LabModule_muestra" AS mu\n'
                     'ON mu.id = mb."idMuestra_id"\n'
                     'LEFT JOIN "LabModule_paso_muestras" AS pm\n'
                     'ON pm.muestra_id = mu.id\n'
                     'LEFT JOIN "LabModule_paso" AS pa\n'
                     'ON pa.id = pm.paso_id\n'
                     'LEFT JOIN "LabModule_protocolo" AS p\n'
                     'ON p.id = pa.protocolo_id\n'
                     'LEFT JOIN "LabModule_mueble" AS m\n'
                     'ON m.id = a.mueble_id\n'
                     'LEFT JOIN "LabModule_muebleenlab" AS ml\n'
                     'ON ml."idMueble_id" = m.id\n'
                     'LEFT JOIN "LabModule_laboratorio" AS l\n'
                     'ON l."idLaboratorio" = ml."idLaboratorio_id"\n'
                     'WHERE m.tipo = \'almacenamiento\'\n')

queryDetalleSolicitudes = ('SELECT \n'
                           '        ml."idLaboratorio_id",\n'
                           '        a."idSistema",\n'
                           '        me.nombre,\n'
                           '        ml."posX",\n'
                           '        ml."posY",\n'
                           '        b.posicion,\n'
                           '        mb."posX" AS "posXMuestra",\n'
                           '        mb."posY" AS "posYMuestra"\n'
                           'FROM "LabModule_solicitud" s\n'
                           'JOIN "LabModule_solicitudmuestra" m\n'
                           'ON s.id = m."solicitud_id"\n'
                           'JOIN "LabModule_muestraenbandeja" mb\n'
                           'ON m."muestra_id" = mb."idMuestra_id"\n'
                           'JOIN "LabModule_bandeja" b\n'
                           'ON mb."idBandeja_id"=b.id\n'
                           'JOIN "LabModule_almacenamiento" a\n'
                           'ON b."almacenamiento_id" = a."idSistema"\n'
                           'JOIN "LabModule_mueble" me\n'
                           'ON a."mueble_id" = me.id\n'
                           'JOIN "LabModule_muebleenlab" ml\n'
                           'ON a."mueble_id" = ml."idMueble_id"\n')
queryListaSolicitudes = ('SELECT \n'
                         '      s.id AS "idSolicitud",\n'
                         '      sm.tipo AS "tipo",\n'
                         '      m.nombre AS "nombreMuestra",\n'
                         '      sm.cantidad AS "cantSolicitada",\n'
                         '      count(mb.id) AS "cantExistente",\n'
                         '      s."fechaActual" AS "fecha",\n'
                         '      u."nombre_usuario" AS "solicitante",\n'
                         '      p.nombre AS "paso",\n'
                         '      p.descripcion AS "descPaso"\n'
                         'FROM "LabModule_solicitud" s\n'
                         'JOIN "LabModule_usuario" u\n'
                         'ON s."solicitante_id" = u.id\n'
                         'JOIN "LabModule_paso" p\n'
                         'ON s."paso_id" = p.id\n'
                         'JOIN "LabModule_solicitudmuestra" sm\n'
                         'ON s.id = sm."solicitud_id"\n'
                         'LEFT JOIN "LabModule_muestraenbandeja" mb\n'
                         'ON sm."muestra_id" = mb."idMuestra_id"\n'
                         'LEFT JOIN "LabModule_muestra" m\n'
                         'ON mb."idMuestra_id" = m.id\n'
                         'WHERE s.estado = \'creada\'\n'
                         'GROUP BY s.id,\n'
                         '         sm.tipo,\n'
                         '	       m.nombre,\n'
                         '         sm.cantidad,\n'
                         '         s."fechaActual",\n'
                         '         u."nombre_usuario",\n'
                         '         p.nombre,\n'
                         '         p.descripcion ')
queryBandejasMuestras = (' SELECT \n'
                         '        ml."idLaboratorio_id",\n'
                         '        a."idSistema",\n'
                         '        me.nombre,\n'
                         '        ml."posX",\n'
                         '        ml."posY",\n'
                         '        b.posicion,\n'
                         '        mb."posX" AS "posXMuestra",\n'
                         '        mb."posY" AS "posYMuestra"\n'
                         'FROM "LabModule_muestraenbandeja" mb\n'
                         'JOIN "LabModule_bandeja" b\n'
                         'ON mb."idBandeja_id"=b.id\n'
                         'JOIN "LabModule_almacenamiento" a\n'
                         'ON b."almacenamiento_id" = a."idSistema"\n'
                         'JOIN "LabModule_mueble" me\n'
                         'ON a."mueble_id" = me.id\n'
                         'JOIN "LabModule_muebleenlab" ml\n'
                         'ON a."mueble_id" = ml."idMueble_id"\n')
queryListaMuestrasAll = ('SELECT\n'
                         '        m.id,\n'
                         '        m.nombre,\n'
                         '        m.valor,\n'
                         '        m."unidadBase",\n'
                         '        count(mb.id) AS "cant_muestras",\n'
                         '        m.controlado\n'
                         'FROM "LabModule_muestra" m\n'
                         'LEFT JOIN "LabModule_muestraenbandeja" mb\n'
                         'ON m.id = mb."idMuestra_id"\n'
                         'GROUP BY m.id,\n'
                         '         m.nombre,\n'
                         '         m.valor,\n'
                         '         m."unidadBase",\n'
                         '         m.controlado\n')
queryListaMuestras = ('SELECT\n'
                      '        m.id,\n'
                      '        m.nombre,\n'
                      '        m.valor,\n'
                      '        m."unidadBase",\n'
                      '        count(mb.id) AS "cant_muestras",\n'
                      '        m.controlado\n'
                      'FROM "LabModule_muestra" m\n'
                      'LEFT JOIN "LabModule_muestraenbandeja" mb\n'
                      'ON m.id = mb."idMuestra_id"\n'
                      'WHERE m.activa = true\n'
                      'GROUP BY m.id,\n'
                      '         m.nombre,\n'
                      '         m.valor,\n'
                      '         m."unidadBase",\n'
                      '         m.controlado\n')
