# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdTypeName', models.CharField(default='', max_length=2, verbose_name='Nombre Tipo Identificaci\xf3n')),
                ('IdTypeDesc', models.CharField(default='', max_length=100, verbose_name='Descripci\xf3n Tipo Identificaci\xf3n')),
            ],
            options={
                'verbose_name': 'Tipo Identificaci\xf3n',
                'verbose_name_plural': 'Tipos de Indentificaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCode', models.CharField(default='', max_length=20, verbose_name='C\xf3digo')),
                ('userRoleName', models.CharField(default='', editable=False, max_length=20, verbose_name='Cargo')),
                ('userGivenName', models.CharField(default='', max_length=50, verbose_name='Nombres')),
                ('userLastName', models.CharField(default='', max_length=50, verbose_name='Apellidos')),
                ('userPhone', models.CharField(default='', max_length=20, verbose_name='Tel\xe9fono')),
                ('userNatIdTypName', models.CharField(default='', editable=False, max_length=20, verbose_name='Tipo Identificaci\xf3n')),
                ('userNatIdNum', models.CharField(default='', max_length=15, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('userNatIdTyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabModule.IdType', verbose_name='Tipo Identificaci\xf3n')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRoleName', models.CharField(default='', max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabModule.UserRole', verbose_name='Cargo'),
        ),
    ]
