# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=1000, verbose_name='Descripcion')),
                ('laboratorio', models.CharField(default='', max_length=100, verbose_name='Laboratorio')),
                ('xPos', models.IntegerField(verbose_name='Posci\xf3n x')),
                ('yPos', models.IntegerField(verbose_name='Posci\xf3n y')),
            ],
            options={
                'verbose_name': 'M\xe1quina',
                'verbose_name_plural': 'M\xe1quinas',
            },
        ),
    ]
