# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabModule', '0002_maquinaprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaprofile',
            name='idSistema',
            field=models.CharField(default='', max_length=20, verbose_name='idSistema'),
        ),
        migrations.AlterField(
            model_name='maquinaprofile',
            name='descripcion',
            field=models.CharField(default='', max_length=1000, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='maquinaprofile',
            name='xPos',
            field=models.IntegerField(verbose_name='Posici\xf3n x'),
        ),
        migrations.AlterField(
            model_name='maquinaprofile',
            name='yPos',
            field=models.IntegerField(verbose_name='Posici\xf3n y'),
        ),
    ]
