# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabModule', '0003_auto_20170315_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaprofile',
            name='imagen',
            field=models.ImageField(default='media/images/image-not-found.jpg', upload_to='media/images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='maquinaprofile',
            name='descripcion',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='maquinaprofile',
            name='idSistema',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaci\xf3n'),
        ),
    ]
