# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabModule', '0004_auto_20170315_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaprofile',
            name='imagen',
            field=models.ImageField(default='images/image-not-found.jpg', upload_to='media/images', verbose_name='Imagen'),
        ),
    ]
