# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabModule', '0006_auto_20170315_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_addMachine', 'Puede agregar maquinas'), ('can_edditMachine', 'Puede editar m\xe1quinas')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
